spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imagebackup?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123~qwer
    
dev:
  redis:
    url: 127.0.0.1
    port: 6379
  batch:
    url:
      setPanoramaImagePool: http://localhost:9090/jenkins/job/CallPanoramaImage/build?token=callPanoramaImage
      setCaptchaImagePool: http://localhost:9090/jenkins/job/setCaptchaImage/build?token=setCaptchaImage
    token: ncaptcha:110b2e66271e48c51ea492ef117bbd34a2
    